import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/features/**/*.{js,ts,jsx,tsx,mdx}',
    '../../packages/shared/src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'inverse-on-surface': '#f4f0e9',
        'on-primary': '#ffffff',
        'tertiary-fixed': '#ffdeaa',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#2a6d75',
        'secondary-container': '#acedf6',
        'error': '#ba1a1a',
        'surface-container-high': '#ece8e1',
        'on-tertiary': '#ffffff',
        'on-tertiary-fixed-variant': '#5f4100',
        'secondary': '#22676f',
        'on-error': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'error-container': '#ffdad6',
        'outline-variant': '#c9c4d0',
        'surface-tint': '#61578f',
        'surface-container-low': '#f7f3ec',
        'surface': '#fdf9f2',
        'on-secondary-fixed-variant': '#004f56',
        'surface-bright': '#fdf9f2',
        'on-primary-fixed-variant': '#493f75',
        'tertiary-container': '#996c04',
        'on-secondary-fixed': '#001f23',
        'inverse-surface': '#31302c',
        'surface-container-highest': '#e6e2db',
        'tertiary-fixed-dim': '#f5bd58',
        'primary-fixed-dim': '#cbbefe',
        'on-background': '#1c1c18',
        'surface-container': '#f1ede6',
        'inverse-primary': '#cbbefe',
        'secondary-fixed': '#acedf6',
        'surface-dim': '#dddad3',
        'primary': '#5e548c',
        'on-primary-fixed': '#1d1147',
        'on-surface': '#1c1c18',
        'on-primary-container': '#fffbff',
        'surface-variant': '#e6e2db',
        'outline': '#797580',
        'on-surface-variant': '#48454f',
        'primary-fixed': '#e6deff',
        'secondary-fixed-dim': '#91d1da',
        'tertiary': '#7a5500',
        'on-tertiary-fixed': '#271900',
        'primary-container': '#776da6',
        'background': '#fdf9f2',
        'on-error-container': '#93000a',
        'on-tertiary-container': '#fffbff',
        // HENU OS Brand cyber accents
        'henu-cyan': '#06B6D4',
        'henu-cyan-light': '#22D3EE',
        'henu-blue': '#3B82F6',
        'henu-gold': '#D9A441',
        'henu-iris': '#887DB8',
        'henu-teal': '#236870',
        'henu-rose': '#C96F61',
        'henu-dark-base': '#11131A',
        'henu-dark-surface': '#181B24',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.125rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '0.875rem',
        'space-lg': '1.5rem',
        'space-xl': '2.25rem',
        'gutter': '1.25rem',
        'margin': '1.75rem',
      },
      fontFamily: {
        sans: ['var(--font-plus-jakarta)', 'Plus Jakarta Sans', 'Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
};

export default config;
