export interface CatalogPresetItem {
  id: string;
  name: string;
  sku: string;
  hsn_sac_code: string;
  default_account: string;
  default_rate: number;
  default_tax_rate: number;
  unit: string;
  category: string;
  description: string;
}

export const CATALOG_PRESET_ITEMS: CatalogPresetItem[] = [
  {
    id: 'itm_001',
    name: 'Dedicated Full-Stack System Architecture & Engineering',
    sku: 'SRV-ARCH-01',
    hsn_sac_code: '998313',
    default_account: 'Sales',
    default_rate: 15000,
    default_tax_rate: 18,
    unit: 'project',
    category: 'Engineering',
    description: 'High-availability bespoke client portal, quotes workbench, and real-time payment gateway integration.',
  },
  {
    id: 'itm_002',
    name: 'Cloud Security Audit & Realtime Telemetry Setup',
    sku: 'SRV-SEC-02',
    hsn_sac_code: '998314',
    default_account: 'Professional Services',
    default_rate: 4500,
    default_tax_rate: 18,
    unit: 'audit',
    category: 'Security',
    description: 'DAST/SAST penetration testing, SOC2 compliance report, and realtime logging infrastructure.',
  },
  {
    id: 'itm_003',
    name: 'Hardware Security Key (FIDO2 Enterprise)',
    sku: 'HW-KEY-001',
    hsn_sac_code: '8471',
    default_account: 'Hardware Sales',
    default_rate: 1200,
    default_tax_rate: 18,
    unit: 'pcs',
    category: 'Hardware',
    description: 'Cryptographic hardware security token for zero-trust IAM authentication.',
  },
  {
    id: 'itm_004',
    name: 'Interactive 3D WebGL / Shader Experience',
    sku: 'SRV-3D-03',
    hsn_sac_code: '998315',
    default_account: 'Creative Design',
    default_rate: 25000,
    default_tax_rate: 18,
    unit: 'project',
    category: 'Creative Design',
    description: 'Custom GPU-accelerated interactive canvas responding to touch gestures and gyroscope parallax.',
  },
  {
    id: 'itm_005',
    name: 'Zero-Trust Supabase & Database Hardening',
    sku: 'SRV-DB-04',
    hsn_sac_code: '998316',
    default_account: 'Security & DevOps',
    default_rate: 32000,
    default_tax_rate: 18,
    unit: 'project',
    category: 'DevOps',
    description: 'Database RLS policies, tamper-proof audit trails, and secret shielding architecture.',
  },
  {
    id: 'itm_006',
    name: 'Standard Graphic Add-on',
    sku: 'ADD-GRA-01',
    hsn_sac_code: '998315',
    default_account: 'Sales',
    default_rate: 189,
    default_tax_rate: 18,
    unit: 'item',
    category: 'Add-on',
    description: 'High-resolution custom vector brand graphic.',
  },
  {
    id: 'itm_007',
    name: 'AI Graphic Add-on',
    sku: 'ADD-AI-02',
    hsn_sac_code: '998315',
    default_account: 'Sales',
    default_rate: 79,
    default_tax_rate: 18,
    unit: 'item',
    category: 'Add-on',
    description: 'AI-generated high-fidelity concept visual.',
  },
  {
    id: 'itm_008',
    name: 'Premium Carousel Add-on',
    sku: 'ADD-CAR-03',
    hsn_sac_code: '998315',
    default_account: 'Sales',
    default_rate: 349,
    default_tax_rate: 18,
    unit: 'item',
    category: 'Add-on',
    description: 'Multi-slide interactive marketing carousel.',
  },
  {
    id: 'itm_009',
    name: 'AI Video (15–30 sec)',
    sku: 'ADD-VID-04',
    hsn_sac_code: '998315',
    default_account: 'Sales',
    default_rate: 397,
    default_tax_rate: 18,
    unit: 'video',
    category: 'Add-on',
    description: 'Short-form cinematic promo video edit.',
  },
  {
    id: 'itm_010',
    name: 'AI Video (30–67 sec)',
    sku: 'ADD-VID-05',
    hsn_sac_code: '998315',
    default_account: 'Sales',
    default_rate: 578,
    default_tax_rate: 18,
    unit: 'video',
    category: 'Add-on',
    description: 'Extended cinematic AI video with voiceover.',
  },
  {
    id: 'itm_011',
    name: 'YouTube Management (Monthly)',
    sku: 'SRV-YT-06',
    hsn_sac_code: '998315',
    default_account: 'Sales',
    default_rate: 5829,
    default_tax_rate: 18,
    unit: 'month',
    category: 'Monthly Retainer',
    description: 'End-to-end channel optimization, metadata, and schedule management.',
  },
  {
    id: 'itm_012',
    name: 'YouTube Editing (Monthly)',
    sku: 'SRV-YTE-07',
    hsn_sac_code: '998315',
    default_account: 'Sales',
    default_rate: 6500,
    default_tax_rate: 18,
    unit: 'month',
    category: 'Monthly Retainer',
    description: 'Weekly long-form and short-form video post-production.',
  },
  {
    id: 'itm_013',
    name: 'Google Maps – Urban (28 days)',
    sku: 'SRV-GMU-08',
    hsn_sac_code: '998315',
    default_account: 'Sales',
    default_rate: 2649,
    default_tax_rate: 18,
    unit: '28 days',
    category: 'Local SEO',
    description: 'Urban Google Business Profile ranking and verification.',
  },
  {
    id: 'itm_014',
    name: 'Google Maps – Rural (28 days)',
    sku: 'SRV-GMR-09',
    hsn_sac_code: '998315',
    default_account: 'Sales',
    default_rate: 979,
    default_tax_rate: 18,
    unit: '28 days',
    category: 'Local SEO',
    description: 'Rural regional business presence and citation setup.',
  },
];
